default: &default
  redis_db: 0

development:
  <<: *default
  redis_host: 127.0.0.1
  redis_port: 6379

production:
  <<: *default
  redis_host: <%= ENV['REDIS_HOST'] || '127.0.0.1' %>
  redis_port: <%= ENV['SIDEKIQ_REDIS_PORT'] || 6379 %>
