default: &default
  redis_db: 1

development:
  <<: *default
  redis_host: 127.0.0.1
  redis_port: 6379

test:
  <<: *default
  redis_host: 127.0.0.1
  redis_port: 6379

production:
  <<: *default
  redis_host: <%= ENV['SIDEKIQ_REDIS_HOST'] %>
  redis_port: <%= ENV['SIDEKIQ_REDIS_PORT'] %>
